### ISSUE TITLE
Missing packagist package 

### ISSUE THREAD

**Issue by ghost** [mnapoli/silly-php-di#1]
Hi, Matthieu! Thank you for Silly, like it a lot!
Unfortunately cannot find mnapoli/silly-php-di on packagist.
It's not a big issue since composer allows to set custom repositories, but it's just not too handy, you know :)

**Comment by ghost** [comment]
Just noticed that you haven't even yet tagged any commits with a stable version number.
Looking forward to it, so I can use it with minimum-stability: stable

**Comment by mnapoli** [comment]
Well I did forgot a few steps here ;)

Sorry about that I'm fixing that

**Comment by mnapoli** [comment]
All should be good now! https://packagist.org/packages/mnapoli/silly-php-di

Thanks for the report

**Comment by ghost** [comment]
Thank you!
