### ISSUE TITLE
Problems in PHP 7.4 with no output or command execution

### ISSUE THREAD

**Issue by opengeek** [mnapoli/silly-php-di#6]
I've noticed this project hasn't been touched in a very long time, and I'm wondering if anyone else is having trouble using the PHP-DI edition of Silly in PHP 7.4. I'm not getting any errors at all, but running `list` or any configured command is seemingly doing absolutely nothing. Does anyone have any thoughts or suggestions? I'm trying to debug into the stack but it's not helping much.

**Comment by opengeek** [comment]
OMG — nevermind. Stupidest move ever after working too many hours. I forgot to add `$app->run()` to my script. SMDH.

**Comment by mnapoli** [comment]
😄  that happens to the best of us!

And yes I use these packages, these are maintained, just there isn't much to do (which I like ^^).
